addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5

language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install g++
  - sudo apt-get install cmake
before_script:
  - git submodule init
  - git submodule update
script:
  - mkdir build
  - cd build
  - cmake -DSOUNDTAILOR_HAS_GTEST=ON -DSOUNDTAILOR_ENABLE_SIMD=OFF ..
  - make clean
  - make
  - valgrind --leak-check=full --track-origins=yes ./soundtailor/tests/soundtailor_tests --gtest_filter=-*.*Perf
