install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    # Informations
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - valgrind
            - cmake
language: cpp
compiler:
  - clang
  - gcc
before_script:
  - git submodule init
  - git submodule update
script:
  - mkdir build
  - cd build
  - cmake -DSOUNDTAILOR_HAS_GTEST=ON -DSOUNDTAILOR_ENABLE_SIMD=OFF ..
  - make clean
  - make
  - valgrind --leak-check=full --track-origins=yes ./soundtailor/tests/soundtailor_tests --gtest_filter=-*.*Perf
